apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: analytic
spec:
  maxReplicas: 5
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: analytic
  targetCPUUtilizationPercentage: 60