apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: core
spec:
  maxReplicas: 5
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: core
  targetCPUUtilizationPercentage: 70