apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytic
  labels:
    app: analytic
spec:
  replicas: 3
  selector:
    matchLabels:
      app: analytic
  template:
    metadata:
      labels:
        app: analytic
    spec:
      containers:
        - name: analytic
          image: distucker/analytic:b9df66e6068b1af8574863693243d4e740fabf1d
          envFrom:
          - secretRef:
              name: analytic-secret          
          resources:
            requests:
              memory: "100Mi"
              cpu: "200m"
            limits:
              memory: "250Mi"
              cpu: "250m"
          ports:
            - containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
