apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytic
  labels:
    app: analytic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytic
  template:
    metadata:
      labels:
        app: analytic
    spec:
      containers:
        - name: analytic
          image: distucker/analytic:image-tag  
          resources:
            requests:
              memory: "64Mi"
              cpu: "64m"
            limits:
              memory: "100Mi"
              cpu: "100m"
          ports:
            - containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
