apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytic
  labels:
    app: analytic
spec:
  replicas: 3
  selector:
    matchLabels:
      app: analytic
  template:
    metadata:
      labels:
        app: analytic
    spec:
      containers:
        - name: analytic
          image: distucker/analytic:61b55b24e556a427c26da34f7faf933b5c4b9a0a
          envFrom:
          - secretRef:
              name: analytic-secret          
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "200Mi"
              cpu: "200m"
          ports:
            - containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
