apiVersion: apps/v1
kind: Deployment
metadata:
  name: core
  labels:
    app: core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core
  template:
    metadata:
      labels:
        app: core
    spec:
      containers:
        - name: core
          image: distucker/core:02522205cf1bb69b98a7578a90e8c84e11775e0b
          resources:
            requests:
              memory: "64Mi"
              cpu: "64m"
            limits:
              memory: "100Mi"
              cpu: "100m"
          ports:
            - containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
