apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: distucker/frontend:1da9d1be3885155c9ecf81e054a93ea314d5bc77
          resources:
            requests:
              memory: "64Mi"
              cpu: "64m"
            limits:
              memory: "100Mi"
              cpu: "100m"
          ports:
            - containerPort: 3000
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 15
